pages_build_output_dir = ".next"
name = "english-teacher-portfolio"
compatibility_date = "2024-12-16"

[[d1_databases]]
binding = "DB"
database_name = "english-portfolio"
database_id = "408917de-195f-42e9-8010-5067b228d9eb"
